package com.ice.shippingservice.Enum;

public enum ErrorCode {
    SHIPMENT_NOT_FOUND,
    SHIPMENT_ACCESS_DENIED,
    SHIPMENT_CANNOT_CANCEL,
    ADDRESS_MAPPING_FAILED,
    CARRIER_API_ERROR,
    INVALID_ADDRESS,
    FEE_CALCULATION_FAILED,
    INVALID_WEBHOOK,
    ORDER_SERVICE_UNAVAILABLE
}
