spring.application.name=order-service

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem

server.port=8085

cart.service.url = http://localhost:8084
user.service.url = http://localhost:8081
payment.service.url = http://localhost:8086
inventory.service.url = http://localhost:8083
internal.secret-token=${INTERNAL_SECRET_TOKEN}

spring.kafka.bootstrap-servers=localhost:9092                                                                                                    
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer                                                      
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer 

spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
