spring.application.name=Product-service

spring.datasource.url=jdbc:postgresql://localhost:5432/product_service_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem

server.port=8082

spring.data.redis.host=localhost
spring.data.redis.port=6379

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=products

internal.secret-token = ${INTERNAL_SECRET_TOKEN}

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=changeme

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer



