spring.application.name=inventory-service

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_service_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem

server.port=8083

internal.secret-token = ${INTERNAL_SECRET_TOKEN}

spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Flash sale settlement job
flash.settlement.interval-ms=60000
flash.settlement.initial-delay-ms=20000

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
