package com.ice.orderservice.Enum;

public enum ErrorCode {
    CHECKOUT_TOKEN_EXPIRED,
    ORDER_NOT_FOUND,
    ORDER_CANNOT_CANCEL,
    INVALID_STATUS_TRANSITION,
    ORDER_ACCESS_DENIED,
    SERVICE_UNAVAILABLE,
    PAYMENT_CREATION_FAILED,
    PAYMENT_REFUND_FAILED,
    PAYMENT_LOOKUP_FAILED,
    PAYMENT_CONFIRM_COD_FAILED,
    INVENTORY_RESERVE_FAILED,
    INVENTORY_RELEASE_FAILED,
    INVENTORY_DEDUCT_FAILED,
    INVENTORY_RETURN_FAILED
}
