package com.ice.orderservice.Enum;

public enum ErrorCode {
    CHECKOUT_TOKEN_EXPIRED,
    ORDER_NOT_FOUND,
    ORDER_CANNOT_CANCEL,
    INVALID_STATUS_TRANSITION,
    ORDER_ACCESS_DENIED,
    SERVICE_UNAVAILABLE
}
